### PR TITLE
Add geometry shader's API to ID3D11DeviceContextExtensions.cs

### PR DESCRIPTION
**Pull request by vmx17**
Add geometry shader API, `GSSetShader()`, `GSSetShaderResouce()` and `GSSetShaderResouces()`.

### CODE REVIEW

**Comment by vmx17** [comment]
Recently I could check geometry shader is working with this code. If you think this valid, please add them.

**Comment by vmx17** [comment]
Sorry I close the request by mistake. Re-open here.

**Comment by vmx17** [comment]
I could comfirm GS was working recently. Thank to fix and merge it. So I may have misunderstool about #47.

**Comment by smourier** [comment]
It's on me, the ToArray here is a DirectN extension method and I just overlooked it :-)

**Pull request merged**
